GRASS_TYPE_START = 1
GRASS_TYPE_END = 5

MONSTERS = [
    {
        "name" : "Unknown",
        "index" : 0,
        "level_start" : 1,
        "base_health" : 5,
        "base_attack" : 5,
        "monster_type" : "G",
    },
    {
        "name" : "Skully",
        "index" : 1,
        "level_start" : 1,
        "base_health" : 5,
        "base_attack" : 5,
        "monster_type" : "G",
        "evolves_to" : 2,
    },
    {
        "name": "Ears",
        "index": 2,
        "level_start": 5,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": None,
    },
    {
        "name": "Hund",
        "index": 3,
        "level_start": 15,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": 4,
    },
    {
        "name": "Hellios",
        "index": 4,
        "level_start": 1,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": None,
    },
    {
        "name": "Slimer",
        "index": 5,
        "level_start": 5,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": 6,
    },
    {
        "name": "Rimuru",
        "index": 6,
        "level_start": 15,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": None,
    },
    {
        "name": "Crimson",
        "index": 7,
        "level_start": 1,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": 8,
    },
    {
        "name": "Foxer",
        "index": 8,
        "level_start": 5,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": 9,
    },
    {
        "name": "Coins",
        "index": 9,
        "level_start": 15,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": None,
    },
]